### ISSUE TITLE
Warning when trying to access https://mydomain.com

### ISSUE THREAD

**Issue by AdamT213** [nodenica/node-heroku-ssl-redirect#11]
When using this package, if I try to access my domain via:
forestfounders.org
http://forestfounders.org
www.foresrfounders.org
http://www.forestfounders.org
https://www.forestfounders.org>
it works as expected. However, if I try to access:
https://forestfounders.org,
I get a warning saying that this site is a potential security risk and urging users not to proceed. This may scare my users. Is this the intended functionality. What can I do about it?

express: 4.16.4
heroku-ssl-redirect: 0.0.4

**Comment by NanoMeko** [comment]
@AdamT213  what was your solution?

**Comment by AdamT213** [comment]
@NanoMeko Nothing to do with this package. Nothing to do with the code at all, actually. We were hosting on GoDaddy. Found a similar issue on the GoDaddy forum with no resolution. Switched to CloudFlare and the problem was fixed. No idea why, but it worked. Gonna go ahead and close this issue.
