### ISSUE TITLE
redirect loop

### ISSUE THREAD

**Issue by hadifarnoud** [nodenica/node-heroku-ssl-redirect#4]
I have a node site with two domains: kamva.ir and kamva.org

this works fine: http://kamva.ir -301-> https://kamva.ir

this doesn't work and says `kamva.org redirected you too many times.`: https://kamva.org or http://kamva.org

what's going on?

**Comment by paulomcnally** [comment]
Hi.

Check if you have NODE_ENV setted to production.

**Comment by hadifarnoud** [comment]
I think I know what happens. it was Cloudflare's fault. it was set to "Flexible" and that was the reason of loop. Cloudflare was trying to connect to the http:// version of the site. 

I now check the domain and allow http on .org domain

**Comment by hadifarnoud** [comment]
I used this code to have ssl redirect for my main domain (kamva.ir) and disable it for kamva.org

```js
function wwwRedirect(req, res, next) {
    if (req.headers.host.slice(0, 4) === 'www.') {
        var newHost = req.headers.host.slice(4);
        return res.redirect(301, req.protocol + '://' + newHost + req.originalUrl);
    } else if (req.headers.host.match(/org/)!==null) {
        console.log('this is ORG! dont use SSL redirect for it');
    } else {
        // enable ssl redirect
        console.log('sslRedirect is enabled');
        app.use(sslRedirect(['production'], 301));
    }
    next();
};

app.use(wwwRedirect);
```

I can see the log 'sslRedirect is enabled' when I goto http://kamva.ir, but it doesn't actually redirect to https://kamva.ir

can you see any issue?
